### ISSUE TITLE
Version 0.120.1 is not in maven yet

### ISSUE THREAD

**Issue by nareshgnT** [googleapis/java-cloud-bom#138]
Still maven repo does not have bom version 0.120.1 which has fix for errorreporting lib

**Comment by chingor13** [comment]
The latest [`com.google.cloud:google-cloud-bom:0.120.2-alpha`](https://search.maven.org/artifact/com.google.cloud/google-cloud-bom/0.120.2-alpha/pom) does have the errorreporting fix
