### ISSUE TITLE
README might mention the other BOM's and explain when to use a particular one.

### ISSUE THREAD

**Issue by lesv** [googleapis/java-cloud-bom#1580]
What the problem is. Example: I'm always frustrated when [...]

**Describe the solution you'd like**
We should mention all the BOM's we produce and explain how to choose between them.  Naive customers might just pick the first one they find.

**Describe alternatives you've considered**
At the very least, provide a link to our docs pages that mention this.

**Comment by elharo** [comment]
The message we should send to customers is use libraries-bom, full stop. It's simple, clear, and accurate. There is no need or reason to choose between the others. libraries-bom is a superset of all the other BOMs, imposes no costs for parts that aren't used, and is less complex than trying to mix and match between the subsidiary BOMs.
