### ISSUE TITLE
Remove Kokoro upper bounds check

### ISSUE THREAD

**Issue by elharo** [googleapis/java-cloud-bom#1659]
Kokoro - Test: BOM Upper Bounds — Build failed 

it duplicates the Github CI check

**Comment by suztomo** [comment]
I see the Kokoro check is not there any more.

<img width="873" alt="Screen Shot 2021-04-28 at 10 29 17" src="https://user-images.githubusercontent.com/28604/116421283-b1bd9e00-a80c-11eb-9ca6-1b7c5de24496.png">

**Comment by suztomo** [comment]
It reappeared.

<img width="923" alt="Screen Shot 2021-04-28 at 10 41 08" src="https://user-images.githubusercontent.com/28604/116423009-4aa0e900-a80e-11eb-908b-36d268405ec7.png">
