### ISSUE TITLE
Investigate maven-flatten-plugin

### ISSUE THREAD

**Issue by chingor13** [googleapis/java-cloud-bom#254]
See if we can use maven-flatten-plugin so that the published google-cloud-bom has all artifact versions at the top level, rather than importing other boms.

We want to keep using imports of other boms for maintenance sake (updating one version at a time when other multi-module artifacts are published)

**Comment by stephaniewang526** [comment]
We have implemented this plugin in Java clients that go into google-cloud-bom. We will not flatten the bom itself.
