### ISSUE TITLE
BOM for test libraries

### ISSUE THREAD

**Issue by laurentgo** [googleapis/java-cloud-bom#4694]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
When writing tests mocking Google Cloud services, one needs to declare some extra dependencies with special classifier like `tests` or `testlib`. Those versions should be in sync with the versions of their respective libraries they are part of, but `libraries-bom` do not include them directly or indirectly, so version of those test dependencies have to be tracked separately.

For example, `com.google.cloud:google-cloud-secretmanager:*:tests` and `com.google.api:gax-grpc:*:testlib` are absent of libraries-bom (but not `com.google.guava:guava-testlib`)

It seems that `libraries-bom` not including those type of dependency is somehow intentional -> https://github.com/googleapis/java-cloud-bom/blob/4e1e9a5dc3dc9605a550ba32bfe97845d82e818d/libraries-bom/pom.xml#L53

**Describe the solution you'd like**
Either include the extra dependencies in libraries-bom or create another BOM to reference them

**Describe alternatives you've considered**
Manual tracking via Google Dashboard

**Additional context**
Any other context or screenshots about the feature request.

**Comment by suztomo** [comment]
That's true. The test libraries are not covered right now. We'll think about the scope and will get back to you.

**Comment by suztomo** [comment]
gax-bom is included in the Libraries BOM. Therefore the test-related artifacts are part of the BOM now.
