### ISSUE TITLE
Publish Javadoc (Cloud RAD) at the time of BOM release

### ISSUE THREAD

**Issue by suztomo** [googleapis/java-cloud-bom#5583]
As of now Cloud RAD document publication occurs each client library repository release. However, the challenge is that the README does not have the correct version at the time of the release. OwlBot Postprocessor updates it _after_ the release to Maven Central. The Libraries BOM release follows the individual library repository release.

To solve the timing problem, we need to process Javadoc artifacts at the same time or after we release the BOM.

CC: @lqiu96  As talked yesterday, I don't expect you implement this but I continue to get your insight on this. If you find something wrong, let me know.

**Comment by ddixit14** [comment]
Hi @suztomo, if I'm understanding this correctly, if we update libraries-bom version in README.md as a part of release-please pr, and then trigger publish_javadocs job as a child job of release job, it solves the issue, right? All we need is the latest version we are releasing in README.md, right?

**Comment by suztomo** [comment]
It's about client libraries, such as java-storage. Not just this repository.

**Comment by ddixit14** [comment]
I believe we can do the same for every module (client-library) in the monorepo? that would solve the problem? it is going to be just one time setup.

**Comment by suztomo** [comment]
There are ~10 client library repositories outside monorepo.

**Comment by alicejli** [comment]
This has been completed.
