### ISSUE TITLE
README.md is not updated for libraries-bom version

### ISSUE THREAD

**Issue by suztomo** [googleapis/java-cloud-bom#5646]
Use extra-files parameter for Release Please config as per https://github.com/googleapis/release-please/issues/1755#issuecomment-1322702025

**Comment by emmileaf** [comment]
Closing as this looks resolved by https://github.com/googleapis/java-cloud-bom/pull/5782, but please re-open if otherwise. Thanks!

**Comment by suztomo** [comment]
Thank you. Yes, it's done.
