### ISSUE TITLE
`google-cloud-bom` `pom.xml` license URL returns HTTP 404

### ISSUE THREAD

**Issue by jamesnetherton** [googleapis/java-cloud-bom#5656]
Seems the license URL in `google-cloud-bom/pom.xml` needs updating. The branch it refers to has been renamed, and even when corrected, the license file is no longer present in the target GitHub project.

https://github.com/googleapis/java-cloud-bom/blob/main/google-cloud-bom/pom.xml#L161

**Comment by lqiu96** [comment]
Thanks for catching this @jamesnetherton! We'll work on fixing this.
