### ISSUE TITLE
Investigate shared-dependencies-convergence failure

### ISSUE THREAD

**Issue by mpeddada1** [googleapis/java-cloud-bom#6523]
The check has been failing since https://github.com/googleapis/java-cloud-bom/pull/6487 with:

![image](https://github.com/googleapis/java-cloud-bom/assets/28604/f730ef8d-ee47-457a-9444-6ef4bc76ffce)

```
java.lang.RuntimeException: Failed to converge dependencies
    at com.google.cloud.tools.opensource.cloudbomdashboard.DashboardMain.main (DashboardMain.java:114)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:750)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:03 min
[INFO] Finished at: 2024-04-03T15:40:15Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project google-cloud-bom-dashboard: An exception occured while executing the Java class. Failed to converge dependencies -> [Help 1]
```

[Desired Outcome] Locally running `DashboardMain` on the `[26.24.0/](https://repo1.maven.org/maven2/com/google/cloud/libraries-bom/26.24.0/) passes with:
```
Shared dependencies converge \o/
Disconnected from the target VM, address: '127.0.0.1:46233', transport: 'socket'

Process finished with exit code 0
```

**Comment by suztomo** [comment]
Memo. It used to print the cause of  errors. Somehow the message in standard error output was discarded in GitHub Actions.

**Comment by mpeddada1** [comment]
Debugging Observations: 
![image](https://github.com/googleapis/java-cloud-bom/assets/66699525/7f45bc3a-bba3-4c9e-a24a-7f4596910d1c)

The shared-dependencies versions end up being empty, which results in `sharedDepsVersions.size()` being 0. https://github.com/googleapis/java-cloud-bom/blob/1eb816758c45a77d7294aa0542aa3e9ae129ac5d/dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java#L218

**How does DashboardMain read the shared-dependencies version?**
Ans. It reads it from the pom.xml of the artifacts. This line looks for the `google-cloud-shared-dependencies` artifact in the dependencyManagement section:
https://github.com/googleapis/java-cloud-bom/blob/721ee5581994fb05f5b4a29652bfde9b58d29164/dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactMavenData.java#L228

The poms in the client libraries were recently changed to use a placeholder for the shared-dependencies version and rely on sdk-platform-java-config to provide the value. ([example](https://github.com/googleapis/java-pubsublite/blob/a8562f7eae0255627c502556dd08a105611093ae/pom.xml#L21))

Potential Solutions:
1) Look for sdk-platform-java-config in `ArtifactMavenData` to get the desired shared-dependencies version. 
2) (Not verified) Perhaps add logic to get effective-pom data and grab the shared-dependencies version from there?

**Comment by suztomo** [comment]
Thank you for solving the mystery. The list was empty. Thus no error message.

**Comment by suztomo** [comment]
On "get effective-pom data", here is the effective-pom of java-pubsublite: https://gist.github.com/suztomo/88c21e4f85a256f747cc1c8275417284. An interesting value is at the properties section:

```
  <properties>
    <auto-value.version>1.10.4</auto-value.version>
    <docRoot>/java/docs/reference/</docRoot>
    <google-cloud-shared-dependencies.version>3.28.1</google-cloud-shared-dependencies.version>
```
