### ISSUE TITLE
FileNotFoundException when searching for poms for `{artifactName}-deps-bom` and `{artifactName}-parent`

### ISSUE THREAD

**Issue by mpeddada1** [googleapis/java-cloud-bom#6560]
Initial investigation of FileNotFoundException:

We recently [added logging ](https://github.com/googleapis/java-cloud-bom/blob/107b1780898577c56f416b38f45b93fc43c2008f/dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactMavenData.java#L264)for exceptions the code was previously silencing them. But I think it is surfacing two issues: 1) It seems to be creating an incorrect pomURL for `google-cloud-storage-control`and `google-cloud-bigtable-stats` (e.g. https://repo1.maven.org/maven2/com/google/cloud/google-cloud-storage-control/2.37.0-alpha/ is available on Maven central) 2) It is looking for `google-cloud-bigtable-stats-deps-bom:2.39.0` when the latest version I could find on maven central is https://repo1.maven.org/maven2/com/google/cloud/google-cloud-bigtable-stats/2.37.0/. The module was removed from the bom in this [PR](https://github.com/googleapis/java-bigtable/pull/2218).

For #1, it looks like this is where the pom is generated: https://github.com/googleapis/java-cloud-bom/blob/107b1780898577c56f416b38f45b93fc43c2008f/dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactMavenData.java#L269-L283

_Originally posted by @mpeddada1 in https://github.com/googleapis/java-cloud-bom/issues/6533#issuecomment-2083801221_

**Comment by mpeddada1** [comment]
The [logic](https://github.com/googleapis/java-cloud-bom/blob/721ee5581994fb05f5b4a29652bfde9b58d29164/dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactMavenData.java#L157-L194) to determine the shared dependencies version first looks at the parentPath, then the pomURL if its not found, releasePath and then depsBomPath. However, the presence of the parent pom is not always guaranteed and it works fine if the version is found in the parentPath but results in the FileNotFoundException if the parent pom is not found (as seen in the case of `google-cloud-storage-control`).

**Comment by suztomo** [comment]
@mpeddada1 Didn't you fix this?

**Comment by mpeddada1** [comment]
@suztomo I have a proposed fix to verify the validity of the url before reading from it: https://github.com/googleapis/java-cloud-bom/pull/6564. This should address the issue of the FileNotFoundException being thrown. 

However, need to do a bit more investigation to improve the logic further to avoid hardcoding certain suffixes for the pom urls ([reference](https://github.com/googleapis/java-cloud-bom/blob/db4265ffa7e23c64ae37d9804394569e4577b3e2/dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactMavenData.java#L172C41-L172C75))

**Comment by mpeddada1** [comment]
Fixed in https://github.com/googleapis/java-cloud-bom/pull/6564
